<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class 02112021UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'firstname' => 'Admin',
                'lastname' => '',
                'email' => 'admin@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$Sj4qAv7AmrWUvethxtBqnOlC3jGm6wxszV0frB6ZueWEOK0e5a3MK',
                'address1' => '',
                'address2' => '',
                'city' => '',
                'state' => '',
                'postal' => '',
                'country' => '',
                'dayphone' => '',
                'evephone' => '',
                'status' => 1,
                'reg_verify' => 0,
                'level' => 0,
                'role' => 1,
                'pick' => 1,
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 => 
            array (
                'id' => 2,
                'firstname' => 'Marc',
                'lastname' => 'Moorman',
                'email' => 'mjrmjr19@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$gj6xN9wStoeWSS87UrCGtOV1KPNvRrhdl2iwv1Rn3x8hTl0Ml0ts2',
                'address1' => 'Po Box 268602',
                'address2' => NULL,
                'city' => 'Weston',
                'state' => 'Florida',
                'postal' => '33326',
                'country' => 'United States',
                'dayphone' => '954-292-3096',
                'evephone' => '954-292-3096',
                'status' => 1,
                'reg_verify' => 0,
                'level' => 0,
                'role' => 2,
                'pick' => 0,
                'token' => NULL,
                'remember_token' => 'lPZoIzz91RjBydGs3RWXsYoteP55ONaJFyVFlcPxmudoiNPUgeBd2cbDfYju',
                'created_at' => '2021-10-26 19:35:41',
                'updated_at' => '2021-10-28 08:59:13',
            ),
            2 => 
            array (
                'id' => 3,
                'firstname' => 'Iza',
                'lastname' => 'Moorman',
                'email' => 'iza@playbooksports.com',
                'email_verified_at' => '2021-10-26 19:49:01',
                'password' => '$2y$10$XKLZOo4EwCZSyHiQk75b6.6qMZzW7us6hJrf8p51zN4YQGfw5m3bq',
                'address1' => 'PO Box 267700',
                'address2' => NULL,
                'city' => 'weston',
                'state' => 'FL',
                'postal' => '33326',
                'country' => 'USA',
                'dayphone' => '954-377-8030',
                'evephone' => '954-377-8030',
                'status' => 1,
                'reg_verify' => 0,
                'level' => 1,
                'role' => 2,
                'pick' => 0,
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-10-26 19:48:36',
                'updated_at' => '2021-10-26 19:49:01',
            ),
            3 => 
            array (
                'id' => 4,
                'firstname' => 'Colleen',
                'lastname' => 'Moorman',
                'email' => 'cm@playbooksports.com',
                'email_verified_at' => '2021-10-26 19:57:09',
                'password' => '$2y$10$aBxQQp2AW89hfl0a2EwQq.MId8VzKnH75m4K5KSmtX/2PF3LMRXE.',
                'address1' => '1087 Shotgun Road',
                'address2' => NULL,
                'city' => 'Sunrise',
                'state' => 'Florida',
                'postal' => '33326',
                'country' => 'USA',
                'dayphone' => '954 377 8000',
                'evephone' => '954 377 8000',
                'status' => 1,
                'reg_verify' => 0,
                'level' => 1,
                'role' => 2,
                'pick' => 0,
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-10-26 19:56:36',
                'updated_at' => '2021-10-26 19:57:10',
            ),
            4 => 
            array (
                'id' => 5,
                'firstname' => 'TdwqugaxXvmZJICV',
                'lastname' => 'ZcNhbgvUyezq',
                'email' => 'wardsuzanna5@gmail.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$bPjQjZywB3tYl9Z2x8oO7ege71UlO/Eyfl3kyjzjBTtm8TRiT0hIS',
                'address1' => 'QRaEkfjvqDpeMHY',
                'address2' => 'ZTESlfvr',
                'city' => 'tZkevfSV',
                'state' => 'jJosVlLHSB',
                'postal' => 'XGZBaMDxmKUcibkq',
                'country' => 'UkPGqMylea',
                'dayphone' => '5053650889',
                'evephone' => '7106308303',
                'status' => 1,
                'reg_verify' => 0,
                'level' => 0,
                'role' => 2,
                'pick' => 0,
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-10-27 12:33:47',
                'updated_at' => '2021-10-27 12:33:47',
            ),
            5 => 
            array (
                'id' => 6,
                'firstname' => 'Maryam',
                'lastname' => 'Hebert',
                'email' => 'rocigih671@koldpak.com',
                'email_verified_at' => '2021-10-27 18:16:31',
                'password' => '$2y$10$iYQo6gL4zwobAel2ut6Vdu5egM6NHZtH5fkFMsPERWq5zxwFp9XuC',
                'address1' => '840 Rocky Cowley Drive',
                'address2' => 'Autem eos est volup',
                'city' => 'Illo asperiores volu',
                'state' => 'Nostrum magna corpor',
                'postal' => 'Nostrum explicabo D',
                'country' => 'Ut deserunt ipsum c',
            'dayphone' => '+1 (493) 594-9287',
            'evephone' => '+1 (807) 622-7754',
                'status' => 1,
                'reg_verify' => 0,
                'level' => 1,
                'role' => 2,
                'pick' => 0,
                'token' => NULL,
                'remember_token' => 'ThkaVqJMql5ybvly5j4rZU5QpuOekZJcVnlb88P0aE4Wo0JcykM1N9PGRd1G',
                'created_at' => '2021-10-27 18:16:06',
                'updated_at' => '2021-10-27 18:17:28',
            ),
            6 => 
            array (
                'id' => 7,
                'firstname' => 'Marc',
                'lastname' => 'Lawrence jr',
                'email' => 'mjr@sportsdata.com',
                'email_verified_at' => NULL,
                'password' => '$2y$10$DXp0k9lYHu1ZDOFKcMxdmOby1ThX9pIuK1pxtXqifJ30W/PKd6ccy',
                'address1' => 'Po Box 268602',
                'address2' => NULL,
                'city' => 'Weston',
                'state' => 'FL',
                'postal' => '33326',
                'country' => 'United States',
                'dayphone' => '9542923096',
                'evephone' => '9542923096',
                'status' => 1,
                'reg_verify' => 0,
                'level' => 0,
                'role' => 2,
                'pick' => 0,
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-10-27 18:17:53',
                'updated_at' => '2021-10-27 18:17:53',
            ),
            7 => 
            array (
                'id' => 8,
                'firstname' => 'John Victor',
                'lastname' => 'Privado',
                'email' => 'teampo2@gmail.com',
                'email_verified_at' => '2021-11-02 00:37:11',
                'password' => '$2y$10$sJOOu9LwvfFNj6Buxqtv.OI/XpUltlohfyh4VZ/5QZsBClewGdX4y',
                'address1' => '25 Ipil Street',
                'address2' => NULL,
                'city' => 'qc',
                'state' => 'ncr',
                'postal' => '1121',
                'country' => 'philippines',
                'dayphone' => '639672939775',
                'evephone' => NULL,
                'status' => 1,
                'reg_verify' => 0,
                'level' => 1,
                'role' => 2,
                'pick' => 0,
                'token' => NULL,
                'remember_token' => NULL,
                'created_at' => '2021-11-02 00:36:59',
                'updated_at' => '2021-11-02 00:37:11',
            ),
        ));
        
        
    }
}